export const TITLE_START = "\x1B]0;";
export const TITLE_END = "\x1B\\";
export const CTRL_C = "\x03";
export const CTRL_D = "\x04";
export const LINE_END = "\x0D";
export const CV_JSON_START = "<CV>"; // ConnectedVariableJson start
export const CV_JSON_END = "</CV>";
export const RARE = "\x1F";
export const SEPARATOR = RARE + "\n" + RARE;
export const SOFT_REBOOT = "soft reboot";
